name: CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  Wrappers-CI:
    strategy:
      matrix:
        demo:
          - hello-world
          - json-rpc
          - simple-storage
          - subgraph-query
          - common-interface
        language:
          - rust
          - assemblyscript
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CI: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13.1'
      - name: Install cue lang
        run: go install cuelang.org/go/cmd/cue@latest
      - name: Check if cue is installed
        run: cue version
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('./${{ matrix.demo }}/wrapper/${{ matrix.language }}/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('./${{ matrix.demo }}/interface/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - id: interfaceExists
        name: Check if Interface exists
        run: 'echo ::set-output name=value::$(node ./scripts/ci/checkInterfaceExists.js ${{ matrix.demo }})'
      - name: Install interface dependencies
        run: yarn --cwd ./${{ matrix.demo }}/interface install --nonInteractive --frozen-lockfile --prefer-offline
        if: ${{ (steps.interfaceExists.outputs.value == 'true') }}
      - name: Build Interface
        run: yarn --cwd ./${{ matrix.demo }}/interface build
        if: ${{ (steps.interfaceExists.outputs.value == 'true') }}
      - name: Deploy interface
        run: yarn --cwd ./${{ matrix.demo }}/interface deploy
        if: ${{ (steps.interfaceExists.outputs.value == 'true') }}
      - name: Install dependencies
        run: yarn --cwd ./${{ matrix.demo }}/wrapper/${{ matrix.language }} install --nonInteractive --frozen-lockfile --prefer-offline
      - name: Build Wrapper
        run: yarn --cwd ./${{ matrix.demo }}/wrapper/${{ matrix.language }} build
      - name: Deploy Wrapper
        run: yarn --cwd ./${{ matrix.demo }}/wrapper/${{ matrix.language }} deploy
      - name: Test Wrapper
        run: yarn --cwd ./${{ matrix.demo }}/wrapper/${{ matrix.language }} test
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.demo }}-${{ matrix.language }}-build-artifact
          path: ./${{ matrix.demo }}/wrapper/${{ matrix.language }}/build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.demo }}-interface-build-artifact
          path: ./${{ matrix.demo }}/interface/build
        if: ${{ (steps.interfaceExists.outputs.value == 'true') }}

  Apps-CI:
    strategy:
      matrix:
        demo:
          - simple-storage
          - hello-world
          - fetch-metadata
          - signer-provider
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CI: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
      - name: Setup Node.js
        uses: actions/setup-node@master
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('./${{ matrix.demo }}/app/**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn --cwd ./${{ matrix.demo }}/app install --nonInteractive --frozen-lockfile --prefer-offline
      - name: Build
        run: yarn --cwd ./${{ matrix.demo }}/app build
      - name: Test
        run: yarn --cwd ./${{ matrix.demo }}/app test
